language: cpp

sudo: false

compiler:
    - g++
os:
    - linux

before_script:
    - wget -q -O - https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz | tar -xz

script:
    - make
