language: cpp

sudo: false

compiler:
    - g++
os:
    - linux

before_script:
    - wget -q -O - https://sourceforge.net/projects/boost/files/boost/1.70.0/boost_1_70_0.tar.gz | tar -xz

script:
    - make
